require:
  - rubocop-rails
  - rubocop-capybara

AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'

Layout/LineLength:
  Exclude:
    - 'config/**/*'

Metrics/BlockLength:
  Exclude:
    - 'config/**/*'

Metrics/MethodLength:
  Max: 50

Rails/I18nLocaleTexts:
  Enabled: false

Rails/LexicallyScopedActionFilter:
  Exclude:
    - 'app/controllers/sessions_controller.rb'

Rails/UniqueValidationWithoutIndex:
  Enabled: false

Style/Documentation:
  Enabled: false
